### ISSUE TITLE
ImportError: libcudart.so.8.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by xxx2974** [Simon4Yan/Learning-via-Translation#17]
Hello, which version of tensorflow do you use? I installed the version 1.0,but when I run ' python train_spgan_demo.py --dataset=market2duke --gpu_id=2',I got the error:ImportError: libcudart.so.8.0: cannot open shared object file: No such file or directory.
 How can I solve it ???

the details :
Traceback (most recent call last):
  File "train_spgan_demo.py", line 5, in <module>
    import Utils.ops as ops
  File "/home/xiaozhenzhen/data/Learning-via-Translation/SPGAN/Utils/ops.py", line 6, in <module>
    import tensorflow as tf
  File "/home/xiaozhenzhen/anaconda2/envs/tf_spgan/lib/python2.7/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/home/xiaozhenzhen/anaconda2/envs/tf_spgan/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 72, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/home/xiaozhenzhen/anaconda2/envs/tf_spgan/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 61, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/home/xiaozhenzhen/anaconda2/envs/tf_spgan/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 28, in <module>
    _pywrap_tensorflow = swig_import_helper()
  File "/home/xiaozhenzhen/anaconda2/envs/tf_spgan/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow', fp, pathname, description)
ImportError: libcudart.so.8.0: cannot open shared object file: No such file or directory

Failed to load the native TensorFlow runtime.

See https://github.com/tensorflow/tensorflow/blob/master/tensorflow/g3doc/get_started/os_setup.md#import_error

**Comment by xxx2974** [comment]
@Simon4Yan ,and my cuda is 9.0

**Comment by Simon4Yan** [comment]
Please try our PyTorch version of SPGAN [here ](https://github.com/Simon4Yan/eSPGAN).
